---
title: "analysis.R"
author: "K. Enevoldsen"
date: "5/3/2021"
output: html_document
---

```{r}
library(tidyverse)
library(kableExtra)

options(dplyr.summarise.inform = FALSE)

df = read_csv("CogSci19_MatchingPennies_TOM_data.csv")
df$tom_level = as.factor(df$tom_level)
df$Framing = factor(df$Framing, levels = c("SlotMachine", "Human"))

```

```{r}
labs <- c('Opponent level 0', 'Opponent level 1', 'Opponent level 2')
names(labs) <- c(0,1,2)
  
ggplot(df, aes(y=player_payoff, x = tom_level, fill=Framing)) + 
  geom_bar(position=position_dodge(0.5), stat="summary") +
  geom_errorbar(position=position_dodge(0.5), stat = "summary", width = 0.5) + 
  labs(y = 'Player payoff', x = 'Opponent level') +
  scale_fill_manual(values=c("red", "blue"), labels = c('Slot machine', 'Human')) +
  theme_bw()

df %>% 
  group_by(participant.code, Framing, tom_level) %>% 
  summarise(player_payoff = sum(player_payoff)) %>% 
  ggplot(aes(y=player_payoff, x=Framing, fill=Framing)) + 
    geom_bar(position="dodge", stat = "summary") + 
    geom_errorbar(position='dodge', stat = "summary", width = 0.5) + 
    labs(y = 'Player payoff', x = 'Trial') +
    facet_wrap(~tom_level, labeller = labeller(tom_level = labs)) + 
    scale_fill_manual(values=c("red", "blue"), labels = c('Slot machine', 'Human'), guide=FALSE) +
    scale_x_discrete(breaks=c('SlotMachine', 'Human'), labels=c("Slot Machine", "Human")) + 
    theme_minimal()

df %>% 
  group_by(Framing, tom_level, participant.code) %>% 
  arrange(trial) %>% 
  mutate(cs_player_payoff = cumsum(player_payoff), cs_tom_payoff=cumsum(tom_payoff), trial=trial-min(trial)) %>%
  group_by(Framing, tom_level, trial) %>% 
  ggplot(aes(x=trial, y =cs_player_payoff, fill= Framing, color = Framing)) +
    geom_hline(yintercept=0, linetype = 'dashed') +
    geom_line(stat = 'summary') + 
    geom_ribbon(stat = 'summary', alpha = 0.15, color = NA) +
    facet_wrap(~tom_level, labeller = labeller(tom_level = labs)) +
    scale_fill_manual(values=c("red", "blue"), labels = c('Slot machine', 'Human')) +
    scale_color_hue(labels = c('Slot machine', 'Human')) +
    labs(y = 'Cumulative player payoff', x = 'Trial') +
    ggtitle('Player payoff across framings and opponent complexities') +
    theme_minimal()



```